### ISSUE TITLE
1.1 Adding a User

### ISSUE THREAD

**Issue by Irisvella** [Irisvella/InventoryPilot#12]
As an admin, I want to be able to create accounts for users so users can access the dashboard. 

Story points: 6
Priority:  1 (high)
Risk: Low 
Child of: #8 

Tasks: 
- [x] Create a frontend interface with fields to fill (username, email, password, role, name, DOB). (1 points)
#34
- [x] Design a database schema for a user (1 points) 
#35
- [x] Create a backend API endpoint for account creation (2 points) 
#36
- [x] Trigger API call on form submission (1 point) 
#37
- [x] Assure error handling in the backend with error codes and message (1 points) 
#38

**Comment by Fatoumatabintabarry** [comment]
Add user completed

**Comment by m-coscia** [comment]
Demo of feature:

https://github.com/user-attachments/assets/2cbfcc2c-d282-406d-aae0-e8bd7547ab28

**Comment by Irisvella** [comment]
Stakeholder signed-off during a demo on January 10th
