### ISSUE TITLE
3.6  Stock Levels by SKU

### ISSUE THREAD

**Issue by yousefenein** [Irisvella/InventoryPilot#26]
As a warehouse manager, I want to monitor stock levels by SKU in real time. 

Story Points: 30
Priority: Medium
Risk: High
Child of: #10 
Estimated Time: 12 hours

Acceptance Criteria:

- The dashboard displays stock levels for all SKUs in real time.
- Alerts are triggered when stock levels for any SKU fall below the defined threshold.
- Users can filter stock levels by category, product type, or warehouse location.

Task Breakdown:

Frontend:

- Create a display for SKU stock levels in real time.
- Add filtering options for category, product type, or location.

Backend:

- Develop API to pull SKU stock data from WMS.
- Implement alert logic for low stock levels.

Testing:

- Blackbox Testing: Simulate low-stock conditions to validate alert triggers.
- Regression Testing: Verify stock levels update correctly across all warehouse locations.

Demo Steps:

**Comment by yousefenein** [comment]
https://github.com/user-attachments/assets/09b672f6-d6ae-44f2-950b-0c9d34d8fef8

**Comment by Irisvella** [comment]
Stakeholder sign-off during a demo on January 10th
