### ISSUE TITLE
Architecture Diagram 

### ISSUE THREAD

**Issue by flo351** [Irisvella/InventoryPilot#29]
Added the Architecture Diagram to describe the application's dependencies to the Wiki

**Comment by flo351** [comment]
[https://app.diagrams.net/#G1G0C81-J5BiRh3LlBK2gV6hFq_miilLDX#%7B%22pageId%22%3A%22zgLA_aLsHk0YXikTm3JI%22%7D]
<img width="794" alt="Screenshot 2024-10-27 at 10 57 55 AM" src="https://github.com/user-attachments/assets/72cbc971-e31e-4045-8292-892db079f1d1">

**Comment by flo351** [comment]
done

**Comment by Fatoumatabintabarry** [comment]
For details , more on the wiki 
![image](https://github.com/user-attachments/assets/dc977fa7-afa9-4aaa-aeec-f8898c7d1d2c)
