### ISSUE TITLE
1.6 View All Users

### ISSUE THREAD

**Issue by m-coscia** [Irisvella/InventoryPilot#41]
As an admin, I want to be able to view all accounts for users so that I can be lead to create, edit, and delete a user account.

Story points: 3
Priority: 1 (high)
Risk: Low
Child of: #8 

Tasks:
- [x] #73
- [x] Create a backend API endpoint for forwarding user information to the correct operations (2 point)
- [ ] Create tests for django and jest
- [ ] Create a search bar to filter out user accounts from admin's view (1 point)

**Comment by m-coscia** [comment]
Quick brainstorming of the layout of functions of the manage users page:
![20241220_154742](https://github.com/user-attachments/assets/1a1d93b5-254b-476e-90d4-e2c321758cfe)

**Comment by m-coscia** [comment]
Figma mockup of this page made in collaboration with @Fatoumatabintabarry and @christa-ux back in early November: [Figma Flow: Manage Users](https://www.figma.com/proto/iIE2NMNcOzIzl1SD818Vjn/CAPSTONE-WAREHOUSE-MANAGEMENT?node-id=116-3729&t=6uwNutcu30tFKkGu-9&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=116%3A3729&show-proto-sidebar=1)

**Comment by m-coscia** [comment]
Demo of the feature :

https://github.com/user-attachments/assets/d565438b-0095-404e-a456-38e8304b8ced

**Comment by Irisvella** [comment]
Stakeholder sign-off during a demo on January 10th
