### ISSUE TITLE
Excel Data Migration 

### ISSUE THREAD

**Issue by Irisvella** [Irisvella/InventoryPilot#47]
Story points: 10
Priority: 1 (high)
Risk: Low
Child of:

Tasks:

- Clean and process data from Excel sheets 

- Migrate data from the Excel sheets to our cloud database 

- Potentially create fake/mock data to populate our database

**Comment by inas-fawzi** [comment]
the PR for creating the tables was not supposed to close this issue, seeing as migrating test data into the tables is still necessary

**Comment by inas-fawzi** [comment]
![Warehouse ERD](https://github.com/user-attachments/assets/f1c20c99-1ea2-47c1-a004-33ecf240c98e)
Updated Version of the ERD after all the changes that have been made.
