### ISSUE TITLE
Entity Relationship Diagram (ERD)

### ISSUE THREAD

**Issue by christa-ux** [Irisvella/InventoryPilot#7]
Created the ERD to visualize how each component of our application interacts with one another.

**Comment by yousefenein** [comment]
[WareHouse ERD.pdf](https://github.com/user-attachments/files/17536970/WareHouse.ERD.pdf)

<img width="1275" alt="image" src="https://github.com/user-attachments/assets/a1026aed-d0ad-4d16-85f7-241b4dd6ed29">

**Comment by yousefenein** [comment]
Draft 1 above, need more info from the stakeholder to make necessary adjustments.

**Comment by Irisvella** [comment]
Finalized version due for: Start of iteration 6

**Comment by Irisvella** [comment]
![image](https://github.com/user-attachments/assets/df216859-34d7-4fc4-8780-63c59c455087)
